name: pw2_proyectolab_less

on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
env:
  DEPLOY_BASE_URL: ${{ vars.DEPLOY_BASE_URL }}
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el Repositorio
        uses: actions/checkout@v4
      - name: Instalar Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Instalar Dependencias del proyecto
        run: npm install
      - name: Compilar el proyecto en dist
        run: npm run build
      - name: Configurar Github Pages para publicar
        uses: actions/configure-pages@v5
      - name: subir compilados (dist)
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'
      - name: publicar Artefactos
        id: deployment
        uses: actions/deploy-pages@v4
